# Akash Network Deployment Configuration for AgentVault
version: "2.0"

services:
  webapp:
    image: agentvault/webapp:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_PRIVATE_KEY=${CDP_PRIVATE_KEY}
      - CDP_NETWORK=base-mainnet
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_KEY=${PINATA_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
      - REDIS_URL=${REDIS_URL}
    command:
      - "npm"
      - "run"
      - "start"

  api:
    image: agentvault/api:latest
    expose:
      - port: 4000
        as: 4000
        to:
          - global: true
    env:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_PRIVATE_KEY=${CDP_PRIVATE_KEY}
      - CDP_NETWORK=base-mainnet
      - X402PAY_WALLET_ADDRESS=${X402PAY_WALLET_ADDRESS}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_KEY=${PINATA_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    command:
      - "npm"
      - "run"
      - "server"

  postgres:
    image: postgres:15-alpine
    expose:
      - port: 5432
        as: 5432
        to:
          - service: webapp
          - service: api
    env:
      - POSTGRES_USER=agentvault
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=agentvault_prod
    
  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - service: webapp
          - service: api
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"

profiles:
  compute:
    webapp:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 10Gi
    api:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          size: 20Gi
    postgres:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 100Gi
    redis:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 10Gi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        webapp:
          denom: uakt
          amount: 100
        api:
          denom: uakt
          amount: 200
        postgres:
          denom: uakt
          amount: 150
        redis:
          denom: uakt
          amount: 50

deployment:
  webapp:
    akash:
      profile: webapp
      count: 2
  api:
    akash:
      profile: api
      count: 2
  postgres:
    akash:
      profile: postgres
      count: 1
  redis:
    akash:
      profile: redis
      count: 1 